### PR TITLE
Add JSON view for AST visualization

### PR DESCRIPTION
**Pull request by barronwei**
This pull request adds a JSON view for the AST on the same pane as well as the option to hide the AST via the `x` and show the AST via the menu. If the AST is already being shown, the menu item is disabled.

### CODE REVIEW

**Review by wlawt — COMMENTED** [review]
Will this PR also include saving states for switching between AST Explorer and JSON?

**Comment by barronwei** [comment]
> Will this PR also include saving states for switching between AST Explorer and JSON?

No, the AST visualization is shown by default.

**Comment by wlawt** [comment]
> > Will this PR also include saving states for switching between AST Explorer and JSON?
> 
> No, the AST visualization is shown by default.

As in, if I expanded the entire AST visualization then switched to JSON then switch back, it results back to default.

**Comment by barronwei** [comment]
> > > Will this PR also include saving states for switching between AST Explorer and JSON?
> > 
> > 
> > No, the AST visualization is shown by default.
> 
> As in, if I expanded the entire AST visualization then switched to JSON then switch back, it results back to default.

Yeah, the two do not share any state, so upon rendering one, the state of the other is wiped.

**Comment by wlawt** [comment]
> > > > Will this PR also include saving states for switching between AST Explorer and JSON?
> > > 
> > > 
> > > No, the AST visualization is shown by default.
> > 
> > 
> > As in, if I expanded the entire AST visualization then switched to JSON then switch back, it results back to default.
> 
> Yeah, the two do not share any state, so upon rendering one, the state of the other is wiped.

Should we consider saving it, so that someone can just come back to where they left off? Maybe we can save this for a future issue

**Review by wlawt — APPROVED** [review]

**Comment by ianjennings** [comment]
> > > > > Will this PR also include saving states for switching between AST Explorer and JSON?
> > > > 
> > > > 
> > > > No, the AST visualization is shown by default.
> > > 
> > > 
> > > As in, if I expanded the entire AST visualization then switched to JSON then switch back, it results back to default.
> > 
> > 
> > Yeah, the two do not share any state, so upon rendering one, the state of the other is wiped.
> 
> Should we consider saving it, so that someone can just come back to where they left off? Maybe we can save this for a future issue

Sounds like an edge case, I say future.

**Pull request merged**
